# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/RV32UI.bd
# Block Designs: The module: 'RV32UI' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_xlslice_2bit_0_0/RV32UI_xlslice_2bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_xlslice_2bit_0_0 || ORIG_REF_NAME==RV32UI_xlslice_2bit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_xlconcat_8_0_0/RV32UI_xlconcat_8_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_xlconcat_8_0_0 || ORIG_REF_NAME==RV32UI_xlconcat_8_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_uart_0_0/RV32UI_uart_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_uart_0_0 || ORIG_REF_NAME==RV32UI_uart_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_timer_0_0/RV32UI_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_timer_0_0 || ORIG_REF_NAME==RV32UI_timer_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_regfile_we_gen_0_0/RV32UI_regfile_we_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_regfile_we_gen_0_0 || ORIG_REF_NAME==RV32UI_regfile_we_gen_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_mem_wb_reg_0_0/RV32UI_mem_wb_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_mem_wb_reg_0_0 || ORIG_REF_NAME==RV32UI_mem_wb_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_constant_zero_0_0/RV32UI_constant_zero_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_constant_zero_0_0 || ORIG_REF_NAME==RV32UI_constant_zero_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_mem_stage_0_0/RV32UI_mem_stage_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_mem_stage_0_0 || ORIG_REF_NAME==RV32UI_mem_stage_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_alu_0_0/RV32UI_alu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_alu_0_0 || ORIG_REF_NAME==RV32UI_alu_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_operand_b_mux_0_0/RV32UI_operand_b_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_operand_b_mux_0_0 || ORIG_REF_NAME==RV32UI_operand_b_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_operand_a_mux_0_0/RV32UI_operand_a_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_operand_a_mux_0_0 || ORIG_REF_NAME==RV32UI_operand_a_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_branch_0_0/RV32UI_branch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_branch_0_0 || ORIG_REF_NAME==RV32UI_branch_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_ex_mem_reg_0/RV32UI_ex_mem_reg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_ex_mem_reg_0 || ORIG_REF_NAME==RV32UI_ex_mem_reg_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_and_0_0/RV32UI_util_vector_and_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_and_0_0 || ORIG_REF_NAME==RV32UI_util_vector_and_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_and_1_0/RV32UI_util_vector_and_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_and_1_0 || ORIG_REF_NAME==RV32UI_util_vector_and_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_forward_mux_0_0/RV32UI_forward_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_forward_mux_0_0 || ORIG_REF_NAME==RV32UI_forward_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_forward_mux_1_0/RV32UI_forward_mux_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_forward_mux_1_0 || ORIG_REF_NAME==RV32UI_forward_mux_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_forward_mux_2_0/RV32UI_forward_mux_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_forward_mux_2_0 || ORIG_REF_NAME==RV32UI_forward_mux_2_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_forwarding_0_0/RV32UI_forwarding_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_forwarding_0_0 || ORIG_REF_NAME==RV32UI_forwarding_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_constant_zero_0_1/RV32UI_constant_zero_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_constant_zero_0_1 || ORIG_REF_NAME==RV32UI_constant_zero_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_wb_mux_0_0/RV32UI_wb_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_wb_mux_0_0 || ORIG_REF_NAME==RV32UI_wb_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_imm_mux_0_0/RV32UI_imm_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_imm_mux_0_0 || ORIG_REF_NAME==RV32UI_imm_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_decoder_0_0/RV32UI_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_decoder_0_0 || ORIG_REF_NAME==RV32UI_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_control_0_0/RV32UI_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_control_0_0 || ORIG_REF_NAME==RV32UI_control_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_id_ex_reg_0/RV32UI_id_ex_reg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_id_ex_reg_0 || ORIG_REF_NAME==RV32UI_id_ex_reg_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_regfile_0_0/RV32UI_regfile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_regfile_0_0 || ORIG_REF_NAME==RV32UI_regfile_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_branch_predictor_btb_0_0/RV32UI_branch_predictor_btb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_branch_predictor_btb_0_0 || ORIG_REF_NAME==RV32UI_branch_predictor_btb_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_pc_to_imem_addr_0_0/RV32UI_pc_to_imem_addr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_pc_to_imem_addr_0_0 || ORIG_REF_NAME==RV32UI_pc_to_imem_addr_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_and_1_1/RV32UI_util_vector_and_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_and_1_1 || ORIG_REF_NAME==RV32UI_util_vector_and_1_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_or_1_0/RV32UI_util_vector_or_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_or_1_0 || ORIG_REF_NAME==RV32UI_util_vector_or_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_not_1_0/RV32UI_util_vector_not_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_not_1_0 || ORIG_REF_NAME==RV32UI_util_vector_not_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_and_0_1/RV32UI_util_vector_and_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_and_0_1 || ORIG_REF_NAME==RV32UI_util_vector_and_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_not_0_0/RV32UI_util_vector_not_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_not_0_0 || ORIG_REF_NAME==RV32UI_util_vector_not_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_or_0_0/RV32UI_util_vector_or_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_or_0_0 || ORIG_REF_NAME==RV32UI_util_vector_or_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_constant_one_0_0/RV32UI_constant_one_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_constant_one_0_0 || ORIG_REF_NAME==RV32UI_constant_one_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_rom_memory_0_0/RV32UI_rom_memory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_rom_memory_0_0 || ORIG_REF_NAME==RV32UI_rom_memory_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_pc_unit_0_0/RV32UI_pc_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_pc_unit_0_0 || ORIG_REF_NAME==RV32UI_pc_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_if_id_reg_0_0/RV32UI_if_id_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_if_id_reg_0_0 || ORIG_REF_NAME==RV32UI_if_id_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_load_use_detection_0_0/RV32UI_load_use_detection_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_load_use_detection_0_0 || ORIG_REF_NAME==RV32UI_load_use_detection_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_priority_branch_OR_l_0_0/RV32UI_priority_branch_OR_l_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_priority_branch_OR_l_0_0 || ORIG_REF_NAME==RV32UI_priority_branch_OR_l_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_mem_bus_registered_0_0/RV32UI_mem_bus_registered_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_mem_bus_registered_0_0 || ORIG_REF_NAME==RV32UI_mem_bus_registered_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_csr_access_unit_0_0/RV32UI_csr_access_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_csr_access_unit_0_0 || ORIG_REF_NAME==RV32UI_csr_access_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_privileged_pc_redire_0_0/RV32UI_privileged_pc_redire_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_privileged_pc_redire_0_0 || ORIG_REF_NAME==RV32UI_privileged_pc_redire_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_system_decoder_0_0/RV32UI_system_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_system_decoder_0_0 || ORIG_REF_NAME==RV32UI_system_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_trap_controller_0_0/RV32UI_trap_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_trap_controller_0_0 || ORIG_REF_NAME==RV32UI_trap_controller_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_exception_mux_0_0/RV32UI_exception_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_exception_mux_0_0 || ORIG_REF_NAME==RV32UI_exception_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_mem_exception_merge_0_0/RV32UI_mem_exception_merge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_mem_exception_merge_0_0 || ORIG_REF_NAME==RV32UI_mem_exception_merge_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_and_0_2/RV32UI_util_vector_and_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_and_0_2 || ORIG_REF_NAME==RV32UI_util_vector_and_0_2} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_not_0_1/RV32UI_util_vector_not_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_not_0_1 || ORIG_REF_NAME==RV32UI_util_vector_not_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_csr_file_0_0/RV32UI_csr_file_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_csr_file_0_0 || ORIG_REF_NAME==RV32UI_csr_file_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_csr_use_detection_0_0/RV32UI_csr_use_detection_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_csr_use_detection_0_0 || ORIG_REF_NAME==RV32UI_csr_use_detection_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_csr_regfile_wb_mux_0_0/RV32UI_csr_regfile_wb_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_csr_regfile_wb_mux_0_0 || ORIG_REF_NAME==RV32UI_csr_regfile_wb_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_ram_data_1_0/RV32UI_ram_data_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_ram_data_1_0 || ORIG_REF_NAME==RV32UI_ram_data_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_gpio_0_0/RV32UI_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_gpio_0_0 || ORIG_REF_NAME==RV32UI_gpio_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_proc_sys_reset_0_0/RV32UI_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_proc_sys_reset_0_0 || ORIG_REF_NAME==RV32UI_proc_sys_reset_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_logic_2_0/RV32UI_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_logic_2_0 || ORIG_REF_NAME==RV32UI_util_vector_logic_2_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_vio_0_0/RV32UI_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_vio_0_0 || ORIG_REF_NAME==RV32UI_vio_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_xlconstant_0_0/RV32UI_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_xlconstant_0_0 || ORIG_REF_NAME==RV32UI_xlconstant_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_zynq_ultra_ps_e_0_0/RV32UI_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==RV32UI_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_logic_2_1/RV32UI_util_vector_logic_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_logic_2_1 || ORIG_REF_NAME==RV32UI_util_vector_logic_2_1} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_proc_sys_reset_0_0/RV32UI_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RV32UI_proc_sys_reset_0_0 || ORIG_REF_NAME==RV32UI_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_proc_sys_reset_0_0/RV32UI_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RV32UI_proc_sys_reset_0_0 || ORIG_REF_NAME==RV32UI_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_vio_0_0/RV32UI_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_vio_0_0 || ORIG_REF_NAME==RV32UI_vio_0_0} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_zynq_ultra_ps_e_0_0/RV32UI_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_zynq_ultra_ps_e_0_0/RV32UI_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RV32UI_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==RV32UI_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/RV32UI_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RV32UI'. Do not add the DONT_TOUCH constraint.

# Block Designs: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/RV32UI.bd
# Block Designs: The module: 'RV32UI' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_xlslice_2bit_0_0/RV32UI_xlslice_2bit_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_xlslice_2bit_0_0 || ORIG_REF_NAME==RV32UI_xlslice_2bit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_xlconcat_8_0_0/RV32UI_xlconcat_8_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_xlconcat_8_0_0 || ORIG_REF_NAME==RV32UI_xlconcat_8_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_uart_0_0/RV32UI_uart_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_uart_0_0 || ORIG_REF_NAME==RV32UI_uart_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_timer_0_0/RV32UI_timer_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_timer_0_0 || ORIG_REF_NAME==RV32UI_timer_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_regfile_we_gen_0_0/RV32UI_regfile_we_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_regfile_we_gen_0_0 || ORIG_REF_NAME==RV32UI_regfile_we_gen_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_mem_wb_reg_0_0/RV32UI_mem_wb_reg_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_mem_wb_reg_0_0 || ORIG_REF_NAME==RV32UI_mem_wb_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_constant_zero_0_0/RV32UI_constant_zero_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_constant_zero_0_0 || ORIG_REF_NAME==RV32UI_constant_zero_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_mem_stage_0_0/RV32UI_mem_stage_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_mem_stage_0_0 || ORIG_REF_NAME==RV32UI_mem_stage_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_alu_0_0/RV32UI_alu_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_alu_0_0 || ORIG_REF_NAME==RV32UI_alu_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_operand_b_mux_0_0/RV32UI_operand_b_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_operand_b_mux_0_0 || ORIG_REF_NAME==RV32UI_operand_b_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_operand_a_mux_0_0/RV32UI_operand_a_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_operand_a_mux_0_0 || ORIG_REF_NAME==RV32UI_operand_a_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_branch_0_0/RV32UI_branch_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_branch_0_0 || ORIG_REF_NAME==RV32UI_branch_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_ex_mem_reg_0/RV32UI_ex_mem_reg_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_ex_mem_reg_0 || ORIG_REF_NAME==RV32UI_ex_mem_reg_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_and_0_0/RV32UI_util_vector_and_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_and_0_0 || ORIG_REF_NAME==RV32UI_util_vector_and_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_and_1_0/RV32UI_util_vector_and_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_and_1_0 || ORIG_REF_NAME==RV32UI_util_vector_and_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_forward_mux_0_0/RV32UI_forward_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_forward_mux_0_0 || ORIG_REF_NAME==RV32UI_forward_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_forward_mux_1_0/RV32UI_forward_mux_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_forward_mux_1_0 || ORIG_REF_NAME==RV32UI_forward_mux_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_forward_mux_2_0/RV32UI_forward_mux_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_forward_mux_2_0 || ORIG_REF_NAME==RV32UI_forward_mux_2_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_forwarding_0_0/RV32UI_forwarding_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_forwarding_0_0 || ORIG_REF_NAME==RV32UI_forwarding_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_constant_zero_0_1/RV32UI_constant_zero_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_constant_zero_0_1 || ORIG_REF_NAME==RV32UI_constant_zero_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_wb_mux_0_0/RV32UI_wb_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_wb_mux_0_0 || ORIG_REF_NAME==RV32UI_wb_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_imm_mux_0_0/RV32UI_imm_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_imm_mux_0_0 || ORIG_REF_NAME==RV32UI_imm_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_decoder_0_0/RV32UI_decoder_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_decoder_0_0 || ORIG_REF_NAME==RV32UI_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_control_0_0/RV32UI_control_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_control_0_0 || ORIG_REF_NAME==RV32UI_control_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_id_ex_reg_0/RV32UI_id_ex_reg_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_id_ex_reg_0 || ORIG_REF_NAME==RV32UI_id_ex_reg_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_regfile_0_0/RV32UI_regfile_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_regfile_0_0 || ORIG_REF_NAME==RV32UI_regfile_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_branch_predictor_btb_0_0/RV32UI_branch_predictor_btb_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_branch_predictor_btb_0_0 || ORIG_REF_NAME==RV32UI_branch_predictor_btb_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_pc_to_imem_addr_0_0/RV32UI_pc_to_imem_addr_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_pc_to_imem_addr_0_0 || ORIG_REF_NAME==RV32UI_pc_to_imem_addr_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_and_1_1/RV32UI_util_vector_and_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_and_1_1 || ORIG_REF_NAME==RV32UI_util_vector_and_1_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_or_1_0/RV32UI_util_vector_or_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_or_1_0 || ORIG_REF_NAME==RV32UI_util_vector_or_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_not_1_0/RV32UI_util_vector_not_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_not_1_0 || ORIG_REF_NAME==RV32UI_util_vector_not_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_and_0_1/RV32UI_util_vector_and_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_and_0_1 || ORIG_REF_NAME==RV32UI_util_vector_and_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_not_0_0/RV32UI_util_vector_not_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_not_0_0 || ORIG_REF_NAME==RV32UI_util_vector_not_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_or_0_0/RV32UI_util_vector_or_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_or_0_0 || ORIG_REF_NAME==RV32UI_util_vector_or_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_constant_one_0_0/RV32UI_constant_one_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_constant_one_0_0 || ORIG_REF_NAME==RV32UI_constant_one_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_rom_memory_0_0/RV32UI_rom_memory_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_rom_memory_0_0 || ORIG_REF_NAME==RV32UI_rom_memory_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_pc_unit_0_0/RV32UI_pc_unit_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_pc_unit_0_0 || ORIG_REF_NAME==RV32UI_pc_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_if_id_reg_0_0/RV32UI_if_id_reg_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_if_id_reg_0_0 || ORIG_REF_NAME==RV32UI_if_id_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_load_use_detection_0_0/RV32UI_load_use_detection_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_load_use_detection_0_0 || ORIG_REF_NAME==RV32UI_load_use_detection_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_priority_branch_OR_l_0_0/RV32UI_priority_branch_OR_l_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_priority_branch_OR_l_0_0 || ORIG_REF_NAME==RV32UI_priority_branch_OR_l_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_mem_bus_registered_0_0/RV32UI_mem_bus_registered_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_mem_bus_registered_0_0 || ORIG_REF_NAME==RV32UI_mem_bus_registered_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_csr_access_unit_0_0/RV32UI_csr_access_unit_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_csr_access_unit_0_0 || ORIG_REF_NAME==RV32UI_csr_access_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_privileged_pc_redire_0_0/RV32UI_privileged_pc_redire_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_privileged_pc_redire_0_0 || ORIG_REF_NAME==RV32UI_privileged_pc_redire_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_system_decoder_0_0/RV32UI_system_decoder_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_system_decoder_0_0 || ORIG_REF_NAME==RV32UI_system_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_trap_controller_0_0/RV32UI_trap_controller_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_trap_controller_0_0 || ORIG_REF_NAME==RV32UI_trap_controller_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_exception_mux_0_0/RV32UI_exception_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_exception_mux_0_0 || ORIG_REF_NAME==RV32UI_exception_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_mem_exception_merge_0_0/RV32UI_mem_exception_merge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_mem_exception_merge_0_0 || ORIG_REF_NAME==RV32UI_mem_exception_merge_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_and_0_2/RV32UI_util_vector_and_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_and_0_2 || ORIG_REF_NAME==RV32UI_util_vector_and_0_2} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_not_0_1/RV32UI_util_vector_not_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_not_0_1 || ORIG_REF_NAME==RV32UI_util_vector_not_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_csr_file_0_0/RV32UI_csr_file_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_csr_file_0_0 || ORIG_REF_NAME==RV32UI_csr_file_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_csr_use_detection_0_0/RV32UI_csr_use_detection_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_csr_use_detection_0_0 || ORIG_REF_NAME==RV32UI_csr_use_detection_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_csr_regfile_wb_mux_0_0/RV32UI_csr_regfile_wb_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_csr_regfile_wb_mux_0_0 || ORIG_REF_NAME==RV32UI_csr_regfile_wb_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_ram_data_1_0/RV32UI_ram_data_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_ram_data_1_0 || ORIG_REF_NAME==RV32UI_ram_data_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_gpio_0_0/RV32UI_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_gpio_0_0 || ORIG_REF_NAME==RV32UI_gpio_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_proc_sys_reset_0_0/RV32UI_proc_sys_reset_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_proc_sys_reset_0_0 || ORIG_REF_NAME==RV32UI_proc_sys_reset_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_logic_2_0/RV32UI_util_vector_logic_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_logic_2_0 || ORIG_REF_NAME==RV32UI_util_vector_logic_2_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_vio_0_0/RV32UI_vio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_vio_0_0 || ORIG_REF_NAME==RV32UI_vio_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_xlconstant_0_0/RV32UI_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_xlconstant_0_0 || ORIG_REF_NAME==RV32UI_xlconstant_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_zynq_ultra_ps_e_0_0/RV32UI_zynq_ultra_ps_e_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==RV32UI_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_util_vector_logic_2_1/RV32UI_util_vector_logic_2_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_util_vector_logic_2_1 || ORIG_REF_NAME==RV32UI_util_vector_logic_2_1} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_proc_sys_reset_0_0/RV32UI_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RV32UI_proc_sys_reset_0_0 || ORIG_REF_NAME==RV32UI_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_proc_sys_reset_0_0/RV32UI_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RV32UI_proc_sys_reset_0_0 || ORIG_REF_NAME==RV32UI_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_vio_0_0/RV32UI_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32UI_vio_0_0 || ORIG_REF_NAME==RV32UI_vio_0_0} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_zynq_ultra_ps_e_0_0/RV32UI_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/ip/RV32UI_zynq_ultra_ps_e_0_0/RV32UI_zynq_ultra_ps_e_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RV32UI_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==RV32UI_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_COCOTB/RISCV.srcs/sources_1/bd/RV32UI/RV32UI_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RV32UI'. Do not add the DONT_TOUCH constraint.
