# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/RISCV_COCOTB.bd
# Block Designs: The module: 'RISCV_COCOTB' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_uart_0_0/RISCV_COCOTB_uart_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_uart_0_0 || ORIG_REF_NAME==RISCV_COCOTB_uart_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_timer_0_0/RISCV_COCOTB_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_timer_0_0 || ORIG_REF_NAME==RISCV_COCOTB_timer_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_regfile_we_gen_0_0/RISCV_COCOTB_regfile_we_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_regfile_we_gen_0_0 || ORIG_REF_NAME==RISCV_COCOTB_regfile_we_gen_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_mem_stage_0_0/RISCV_COCOTB_mem_stage_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_mem_stage_0_0 || ORIG_REF_NAME==RISCV_COCOTB_mem_stage_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_mem_wb_reg_0_0/RISCV_COCOTB_mem_wb_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_mem_wb_reg_0_0 || ORIG_REF_NAME==RISCV_COCOTB_mem_wb_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_alu_0_0/RISCV_COCOTB_alu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_alu_0_0 || ORIG_REF_NAME==RISCV_COCOTB_alu_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_operand_b_mux_0_0/RISCV_COCOTB_operand_b_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_operand_b_mux_0_0 || ORIG_REF_NAME==RISCV_COCOTB_operand_b_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_operand_a_mux_0_0/RISCV_COCOTB_operand_a_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_operand_a_mux_0_0 || ORIG_REF_NAME==RISCV_COCOTB_operand_a_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_forward_mux_0_0/RISCV_COCOTB_forward_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_forward_mux_0_0 || ORIG_REF_NAME==RISCV_COCOTB_forward_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_forward_mux_1_0/RISCV_COCOTB_forward_mux_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_forward_mux_1_0 || ORIG_REF_NAME==RISCV_COCOTB_forward_mux_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_forward_mux_2_0/RISCV_COCOTB_forward_mux_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_forward_mux_2_0 || ORIG_REF_NAME==RISCV_COCOTB_forward_mux_2_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_forwarding_0_0/RISCV_COCOTB_forwarding_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_forwarding_0_0 || ORIG_REF_NAME==RISCV_COCOTB_forwarding_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_branch_0_0/RISCV_COCOTB_branch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_branch_0_0 || ORIG_REF_NAME==RISCV_COCOTB_branch_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_ex_mem_reg_0/RISCV_COCOTB_ex_mem_reg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_ex_mem_reg_0 || ORIG_REF_NAME==RISCV_COCOTB_ex_mem_reg_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_wb_mux_0_0/RISCV_COCOTB_wb_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_wb_mux_0_0 || ORIG_REF_NAME==RISCV_COCOTB_wb_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_regfile_0_0/RISCV_COCOTB_regfile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_regfile_0_0 || ORIG_REF_NAME==RISCV_COCOTB_regfile_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_imm_mux_0_0/RISCV_COCOTB_imm_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_imm_mux_0_0 || ORIG_REF_NAME==RISCV_COCOTB_imm_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_decoder_0_0/RISCV_COCOTB_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_decoder_0_0 || ORIG_REF_NAME==RISCV_COCOTB_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_control_0_0/RISCV_COCOTB_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_control_0_0 || ORIG_REF_NAME==RISCV_COCOTB_control_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_id_ex_reg_0/RISCV_COCOTB_id_ex_reg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_id_ex_reg_0 || ORIG_REF_NAME==RISCV_COCOTB_id_ex_reg_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_branch_predictor_btb_0_0/RISCV_COCOTB_branch_predictor_btb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_branch_predictor_btb_0_0 || ORIG_REF_NAME==RISCV_COCOTB_branch_predictor_btb_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_pc_unit_0_0/RISCV_COCOTB_pc_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_pc_unit_0_0 || ORIG_REF_NAME==RISCV_COCOTB_pc_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_pc_to_imem_addr_0_0/RISCV_COCOTB_pc_to_imem_addr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_pc_to_imem_addr_0_0 || ORIG_REF_NAME==RISCV_COCOTB_pc_to_imem_addr_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_if_id_reg_0_0/RISCV_COCOTB_if_id_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_if_id_reg_0_0 || ORIG_REF_NAME==RISCV_COCOTB_if_id_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_load_use_detection_0_0/RISCV_COCOTB_load_use_detection_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_load_use_detection_0_0 || ORIG_REF_NAME==RISCV_COCOTB_load_use_detection_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_priority_branch_OR_l_0_0/RISCV_COCOTB_priority_branch_OR_l_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_priority_branch_OR_l_0_0 || ORIG_REF_NAME==RISCV_COCOTB_priority_branch_OR_l_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_mem_bus_registered_0_0/RISCV_COCOTB_mem_bus_registered_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_mem_bus_registered_0_0 || ORIG_REF_NAME==RISCV_COCOTB_mem_bus_registered_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_csr_access_unit_0_0/RISCV_COCOTB_csr_access_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_csr_access_unit_0_0 || ORIG_REF_NAME==RISCV_COCOTB_csr_access_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_privileged_pc_redire_0_0/RISCV_COCOTB_privileged_pc_redire_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_privileged_pc_redire_0_0 || ORIG_REF_NAME==RISCV_COCOTB_privileged_pc_redire_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_system_decoder_0_0/RISCV_COCOTB_system_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_system_decoder_0_0 || ORIG_REF_NAME==RISCV_COCOTB_system_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_csr_file_0_0/RISCV_COCOTB_csr_file_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_csr_file_0_0 || ORIG_REF_NAME==RISCV_COCOTB_csr_file_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_csr_regfile_wb_mux_0_0/RISCV_COCOTB_csr_regfile_wb_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_csr_regfile_wb_mux_0_0 || ORIG_REF_NAME==RISCV_COCOTB_csr_regfile_wb_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_trap_controller_0_0/RISCV_COCOTB_trap_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_trap_controller_0_0 || ORIG_REF_NAME==RISCV_COCOTB_trap_controller_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_exception_mux_0_0/RISCV_COCOTB_exception_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_exception_mux_0_0 || ORIG_REF_NAME==RISCV_COCOTB_exception_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_mem_exception_merge_0_0/RISCV_COCOTB_mem_exception_merge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_mem_exception_merge_0_0 || ORIG_REF_NAME==RISCV_COCOTB_mem_exception_merge_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_gpio_0_0/RISCV_COCOTB_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_gpio_0_0 || ORIG_REF_NAME==RISCV_COCOTB_gpio_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_ram_data_1_0/RISCV_COCOTB_ram_data_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_ram_data_1_0 || ORIG_REF_NAME==RISCV_COCOTB_ram_data_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_and_0_0/RISCV_COCOTB_util_vector_and_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_and_0_0 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_and_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_not_0_0/RISCV_COCOTB_util_vector_not_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_not_0_0 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_not_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_and_0_1/RISCV_COCOTB_util_vector_and_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_and_0_1 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_and_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_or_0_0/RISCV_COCOTB_util_vector_or_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_or_0_0 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_or_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_or_0_1/RISCV_COCOTB_util_vector_or_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_or_0_1 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_or_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_not_0_1/RISCV_COCOTB_util_vector_not_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_not_0_1 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_not_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_constant_one_0_0/RISCV_COCOTB_constant_one_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_constant_one_0_0 || ORIG_REF_NAME==RISCV_COCOTB_constant_one_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_rom_memory_0_0/RISCV_COCOTB_rom_memory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_rom_memory_0_0 || ORIG_REF_NAME==RISCV_COCOTB_rom_memory_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_and_0_2/RISCV_COCOTB_util_vector_and_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_and_0_2 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_and_0_2} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_and_0_3/RISCV_COCOTB_util_vector_and_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_and_0_3 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_and_0_3} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_constant_zero_0_1/RISCV_COCOTB_constant_zero_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_constant_zero_0_1 || ORIG_REF_NAME==RISCV_COCOTB_constant_zero_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_xlconcat_8_0_0/RISCV_COCOTB_xlconcat_8_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_xlconcat_8_0_0 || ORIG_REF_NAME==RISCV_COCOTB_xlconcat_8_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_and_0_4/RISCV_COCOTB_util_vector_and_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_and_0_4 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_and_0_4} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_not_0_2/RISCV_COCOTB_util_vector_not_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_not_0_2 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_not_0_2} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_xlslice_2bit_0_0/RISCV_COCOTB_xlslice_2bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_xlslice_2bit_0_0 || ORIG_REF_NAME==RISCV_COCOTB_xlslice_2bit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_csr_use_detection_0_0/RISCV_COCOTB_csr_use_detection_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_csr_use_detection_0_0 || ORIG_REF_NAME==RISCV_COCOTB_csr_use_detection_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_constant_zero_0_2/RISCV_COCOTB_constant_zero_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_constant_zero_0_2 || ORIG_REF_NAME==RISCV_COCOTB_constant_zero_0_2} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/RISCV_COCOTB_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_COCOTB'. Do not add the DONT_TOUCH constraint.

# Block Designs: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/RISCV_COCOTB.bd
# Block Designs: The module: 'RISCV_COCOTB' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_uart_0_0/RISCV_COCOTB_uart_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_uart_0_0 || ORIG_REF_NAME==RISCV_COCOTB_uart_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_timer_0_0/RISCV_COCOTB_timer_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_timer_0_0 || ORIG_REF_NAME==RISCV_COCOTB_timer_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_regfile_we_gen_0_0/RISCV_COCOTB_regfile_we_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_regfile_we_gen_0_0 || ORIG_REF_NAME==RISCV_COCOTB_regfile_we_gen_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_mem_stage_0_0/RISCV_COCOTB_mem_stage_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_mem_stage_0_0 || ORIG_REF_NAME==RISCV_COCOTB_mem_stage_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_mem_wb_reg_0_0/RISCV_COCOTB_mem_wb_reg_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_mem_wb_reg_0_0 || ORIG_REF_NAME==RISCV_COCOTB_mem_wb_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_alu_0_0/RISCV_COCOTB_alu_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_alu_0_0 || ORIG_REF_NAME==RISCV_COCOTB_alu_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_operand_b_mux_0_0/RISCV_COCOTB_operand_b_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_operand_b_mux_0_0 || ORIG_REF_NAME==RISCV_COCOTB_operand_b_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_operand_a_mux_0_0/RISCV_COCOTB_operand_a_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_operand_a_mux_0_0 || ORIG_REF_NAME==RISCV_COCOTB_operand_a_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_forward_mux_0_0/RISCV_COCOTB_forward_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_forward_mux_0_0 || ORIG_REF_NAME==RISCV_COCOTB_forward_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_forward_mux_1_0/RISCV_COCOTB_forward_mux_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_forward_mux_1_0 || ORIG_REF_NAME==RISCV_COCOTB_forward_mux_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_forward_mux_2_0/RISCV_COCOTB_forward_mux_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_forward_mux_2_0 || ORIG_REF_NAME==RISCV_COCOTB_forward_mux_2_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_forwarding_0_0/RISCV_COCOTB_forwarding_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_forwarding_0_0 || ORIG_REF_NAME==RISCV_COCOTB_forwarding_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_branch_0_0/RISCV_COCOTB_branch_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_branch_0_0 || ORIG_REF_NAME==RISCV_COCOTB_branch_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_ex_mem_reg_0/RISCV_COCOTB_ex_mem_reg_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_ex_mem_reg_0 || ORIG_REF_NAME==RISCV_COCOTB_ex_mem_reg_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_wb_mux_0_0/RISCV_COCOTB_wb_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_wb_mux_0_0 || ORIG_REF_NAME==RISCV_COCOTB_wb_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_regfile_0_0/RISCV_COCOTB_regfile_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_regfile_0_0 || ORIG_REF_NAME==RISCV_COCOTB_regfile_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_imm_mux_0_0/RISCV_COCOTB_imm_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_imm_mux_0_0 || ORIG_REF_NAME==RISCV_COCOTB_imm_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_decoder_0_0/RISCV_COCOTB_decoder_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_decoder_0_0 || ORIG_REF_NAME==RISCV_COCOTB_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_control_0_0/RISCV_COCOTB_control_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_control_0_0 || ORIG_REF_NAME==RISCV_COCOTB_control_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_id_ex_reg_0/RISCV_COCOTB_id_ex_reg_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_id_ex_reg_0 || ORIG_REF_NAME==RISCV_COCOTB_id_ex_reg_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_branch_predictor_btb_0_0/RISCV_COCOTB_branch_predictor_btb_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_branch_predictor_btb_0_0 || ORIG_REF_NAME==RISCV_COCOTB_branch_predictor_btb_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_pc_unit_0_0/RISCV_COCOTB_pc_unit_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_pc_unit_0_0 || ORIG_REF_NAME==RISCV_COCOTB_pc_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_pc_to_imem_addr_0_0/RISCV_COCOTB_pc_to_imem_addr_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_pc_to_imem_addr_0_0 || ORIG_REF_NAME==RISCV_COCOTB_pc_to_imem_addr_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_if_id_reg_0_0/RISCV_COCOTB_if_id_reg_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_if_id_reg_0_0 || ORIG_REF_NAME==RISCV_COCOTB_if_id_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_load_use_detection_0_0/RISCV_COCOTB_load_use_detection_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_load_use_detection_0_0 || ORIG_REF_NAME==RISCV_COCOTB_load_use_detection_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_priority_branch_OR_l_0_0/RISCV_COCOTB_priority_branch_OR_l_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_priority_branch_OR_l_0_0 || ORIG_REF_NAME==RISCV_COCOTB_priority_branch_OR_l_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_mem_bus_registered_0_0/RISCV_COCOTB_mem_bus_registered_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_mem_bus_registered_0_0 || ORIG_REF_NAME==RISCV_COCOTB_mem_bus_registered_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_csr_access_unit_0_0/RISCV_COCOTB_csr_access_unit_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_csr_access_unit_0_0 || ORIG_REF_NAME==RISCV_COCOTB_csr_access_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_privileged_pc_redire_0_0/RISCV_COCOTB_privileged_pc_redire_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_privileged_pc_redire_0_0 || ORIG_REF_NAME==RISCV_COCOTB_privileged_pc_redire_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_system_decoder_0_0/RISCV_COCOTB_system_decoder_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_system_decoder_0_0 || ORIG_REF_NAME==RISCV_COCOTB_system_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_csr_file_0_0/RISCV_COCOTB_csr_file_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_csr_file_0_0 || ORIG_REF_NAME==RISCV_COCOTB_csr_file_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_csr_regfile_wb_mux_0_0/RISCV_COCOTB_csr_regfile_wb_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_csr_regfile_wb_mux_0_0 || ORIG_REF_NAME==RISCV_COCOTB_csr_regfile_wb_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_trap_controller_0_0/RISCV_COCOTB_trap_controller_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_trap_controller_0_0 || ORIG_REF_NAME==RISCV_COCOTB_trap_controller_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_exception_mux_0_0/RISCV_COCOTB_exception_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_exception_mux_0_0 || ORIG_REF_NAME==RISCV_COCOTB_exception_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_mem_exception_merge_0_0/RISCV_COCOTB_mem_exception_merge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_mem_exception_merge_0_0 || ORIG_REF_NAME==RISCV_COCOTB_mem_exception_merge_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_gpio_0_0/RISCV_COCOTB_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_gpio_0_0 || ORIG_REF_NAME==RISCV_COCOTB_gpio_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_ram_data_1_0/RISCV_COCOTB_ram_data_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_ram_data_1_0 || ORIG_REF_NAME==RISCV_COCOTB_ram_data_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_and_0_0/RISCV_COCOTB_util_vector_and_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_and_0_0 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_and_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_not_0_0/RISCV_COCOTB_util_vector_not_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_not_0_0 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_not_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_and_0_1/RISCV_COCOTB_util_vector_and_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_and_0_1 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_and_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_or_0_0/RISCV_COCOTB_util_vector_or_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_or_0_0 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_or_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_or_0_1/RISCV_COCOTB_util_vector_or_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_or_0_1 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_or_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_not_0_1/RISCV_COCOTB_util_vector_not_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_not_0_1 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_not_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_constant_one_0_0/RISCV_COCOTB_constant_one_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_constant_one_0_0 || ORIG_REF_NAME==RISCV_COCOTB_constant_one_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_rom_memory_0_0/RISCV_COCOTB_rom_memory_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_rom_memory_0_0 || ORIG_REF_NAME==RISCV_COCOTB_rom_memory_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_and_0_2/RISCV_COCOTB_util_vector_and_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_and_0_2 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_and_0_2} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_and_0_3/RISCV_COCOTB_util_vector_and_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_and_0_3 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_and_0_3} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_constant_zero_0_1/RISCV_COCOTB_constant_zero_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_constant_zero_0_1 || ORIG_REF_NAME==RISCV_COCOTB_constant_zero_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_xlconcat_8_0_0/RISCV_COCOTB_xlconcat_8_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_xlconcat_8_0_0 || ORIG_REF_NAME==RISCV_COCOTB_xlconcat_8_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_and_0_4/RISCV_COCOTB_util_vector_and_0_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_and_0_4 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_and_0_4} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_util_vector_not_0_2/RISCV_COCOTB_util_vector_not_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_util_vector_not_0_2 || ORIG_REF_NAME==RISCV_COCOTB_util_vector_not_0_2} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_xlslice_2bit_0_0/RISCV_COCOTB_xlslice_2bit_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_xlslice_2bit_0_0 || ORIG_REF_NAME==RISCV_COCOTB_xlslice_2bit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_csr_use_detection_0_0/RISCV_COCOTB_csr_use_detection_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_csr_use_detection_0_0 || ORIG_REF_NAME==RISCV_COCOTB_csr_use_detection_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/ip/RISCV_COCOTB_constant_zero_0_2/RISCV_COCOTB_constant_zero_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_COCOTB_constant_zero_0_2 || ORIG_REF_NAME==RISCV_COCOTB_constant_zero_0_2} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/RISCV.srcs/sources_1/bd/RISCV_COCOTB/RISCV_COCOTB_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_COCOTB'. Do not add the DONT_TOUCH constraint.
