# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/BASIC.bd
# Block Designs: The module: 'BASIC' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_pc_unit_0_0/BASIC_pc_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_pc_unit_0_0 || ORIG_REF_NAME==BASIC_pc_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_zynq_ultra_ps_e_0_0/BASIC_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==BASIC_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_proc_sys_reset_0_0/BASIC_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_proc_sys_reset_0_0 || ORIG_REF_NAME==BASIC_proc_sys_reset_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_xlconstant_0_0/BASIC_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_xlconstant_0_0 || ORIG_REF_NAME==BASIC_xlconstant_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_blk_mem_gen_0_0/BASIC_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_blk_mem_gen_0_0 || ORIG_REF_NAME==BASIC_blk_mem_gen_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_xlconstant_1_0/BASIC_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_xlconstant_1_0 || ORIG_REF_NAME==BASIC_xlconstant_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_pc_to_imem_addr_0_0/BASIC_pc_to_imem_addr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_pc_to_imem_addr_0_0 || ORIG_REF_NAME==BASIC_pc_to_imem_addr_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_if_id_reg_0_0/BASIC_if_id_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_if_id_reg_0_0 || ORIG_REF_NAME==BASIC_if_id_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_xlconstant_2_0/BASIC_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_xlconstant_2_0 || ORIG_REF_NAME==BASIC_xlconstant_2_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_decoder_0_0/BASIC_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_decoder_0_0 || ORIG_REF_NAME==BASIC_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_control_0_0/BASIC_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_control_0_0 || ORIG_REF_NAME==BASIC_control_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_regfile_0_0/BASIC_regfile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_regfile_0_0 || ORIG_REF_NAME==BASIC_regfile_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_imm_mux_0_0/BASIC_imm_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_imm_mux_0_0 || ORIG_REF_NAME==BASIC_imm_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_id_ex_reg_0_0/BASIC_id_ex_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_id_ex_reg_0_0 || ORIG_REF_NAME==BASIC_id_ex_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_alu_0_0/BASIC_alu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_alu_0_0 || ORIG_REF_NAME==BASIC_alu_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_forwarding_0_0/BASIC_forwarding_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_forwarding_0_0 || ORIG_REF_NAME==BASIC_forwarding_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_forward_mux_0_0/BASIC_forward_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_forward_mux_0_0 || ORIG_REF_NAME==BASIC_forward_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_operand_b_mux_0_0/BASIC_operand_b_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_operand_b_mux_0_0 || ORIG_REF_NAME==BASIC_operand_b_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_operand_a_mux_0_0/BASIC_operand_a_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_operand_a_mux_0_0 || ORIG_REF_NAME==BASIC_operand_a_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_forward_mux_0_1/BASIC_forward_mux_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_forward_mux_0_1 || ORIG_REF_NAME==BASIC_forward_mux_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_branch_0_0/BASIC_branch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_branch_0_0 || ORIG_REF_NAME==BASIC_branch_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ex_mem_reg_1_0/BASIC_ex_mem_reg_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_ex_mem_reg_1_0 || ORIG_REF_NAME==BASIC_ex_mem_reg_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_mem_stage_0_0/BASIC_mem_stage_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_mem_stage_0_0 || ORIG_REF_NAME==BASIC_mem_stage_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ram_data_1_0/BASIC_ram_data_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_ram_data_1_0 || ORIG_REF_NAME==BASIC_ram_data_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_load_extender_0_0/BASIC_load_extender_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_load_extender_0_0 || ORIG_REF_NAME==BASIC_load_extender_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_xlslice_0_0/BASIC_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_xlslice_0_0 || ORIG_REF_NAME==BASIC_xlslice_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_mem_wb_reg_0_0/BASIC_mem_wb_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_mem_wb_reg_0_0 || ORIG_REF_NAME==BASIC_mem_wb_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_logic_0_0/BASIC_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_logic_0_0 || ORIG_REF_NAME==BASIC_util_vector_logic_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_wb_mux_0_0/BASIC_wb_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_wb_mux_0_0 || ORIG_REF_NAME==BASIC_wb_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_logic_0_1/BASIC_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_logic_0_1 || ORIG_REF_NAME==BASIC_util_vector_logic_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_logic_1_0/BASIC_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_logic_1_0 || ORIG_REF_NAME==BASIC_util_vector_logic_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_load_use_detection_0_0/BASIC_load_use_detection_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_load_use_detection_0_0 || ORIG_REF_NAME==BASIC_load_use_detection_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_priority_branch_OR_l_0_0/BASIC_priority_branch_OR_l_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_priority_branch_OR_l_0_0 || ORIG_REF_NAME==BASIC_priority_branch_OR_l_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_xlconstant_2_1/BASIC_xlconstant_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_xlconstant_2_1 || ORIG_REF_NAME==BASIC_xlconstant_2_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ila_0_0/BASIC_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_ila_0_0 || ORIG_REF_NAME==BASIC_ila_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_vio_0_0/BASIC_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_vio_0_0 || ORIG_REF_NAME==BASIC_vio_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_logic_2_0/BASIC_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_logic_2_0 || ORIG_REF_NAME==BASIC_util_vector_logic_2_0} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_zynq_ultra_ps_e_0_0/BASIC_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_zynq_ultra_ps_e_0_0/BASIC_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BASIC_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==BASIC_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_proc_sys_reset_0_0/BASIC_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BASIC_proc_sys_reset_0_0 || ORIG_REF_NAME==BASIC_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_proc_sys_reset_0_0/BASIC_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BASIC_proc_sys_reset_0_0 || ORIG_REF_NAME==BASIC_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_blk_mem_gen_0_0/BASIC_blk_mem_gen_0_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BASIC_ila_0_0 || ORIG_REF_NAME==BASIC_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BASIC_ila_0_0 || ORIG_REF_NAME==BASIC_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ila_0_0/BASIC_ila_0_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_vio_0_0/BASIC_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_vio_0_0 || ORIG_REF_NAME==BASIC_vio_0_0} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_vio_0_0/BASIC_vio_0_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/BASIC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BASIC'. Do not add the DONT_TOUCH constraint.

# Block Designs: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/BASIC.bd
# Block Designs: The module: 'BASIC' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_pc_unit_0_0/BASIC_pc_unit_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_pc_unit_0_0 || ORIG_REF_NAME==BASIC_pc_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_zynq_ultra_ps_e_0_0/BASIC_zynq_ultra_ps_e_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==BASIC_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_proc_sys_reset_0_0/BASIC_proc_sys_reset_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_proc_sys_reset_0_0 || ORIG_REF_NAME==BASIC_proc_sys_reset_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_xlconstant_0_0/BASIC_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_xlconstant_0_0 || ORIG_REF_NAME==BASIC_xlconstant_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_blk_mem_gen_0_0/BASIC_blk_mem_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_blk_mem_gen_0_0 || ORIG_REF_NAME==BASIC_blk_mem_gen_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_xlconstant_1_0/BASIC_xlconstant_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_xlconstant_1_0 || ORIG_REF_NAME==BASIC_xlconstant_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_pc_to_imem_addr_0_0/BASIC_pc_to_imem_addr_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_pc_to_imem_addr_0_0 || ORIG_REF_NAME==BASIC_pc_to_imem_addr_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_if_id_reg_0_0/BASIC_if_id_reg_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_if_id_reg_0_0 || ORIG_REF_NAME==BASIC_if_id_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_xlconstant_2_0/BASIC_xlconstant_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_xlconstant_2_0 || ORIG_REF_NAME==BASIC_xlconstant_2_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_decoder_0_0/BASIC_decoder_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_decoder_0_0 || ORIG_REF_NAME==BASIC_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_control_0_0/BASIC_control_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_control_0_0 || ORIG_REF_NAME==BASIC_control_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_regfile_0_0/BASIC_regfile_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_regfile_0_0 || ORIG_REF_NAME==BASIC_regfile_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_imm_mux_0_0/BASIC_imm_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_imm_mux_0_0 || ORIG_REF_NAME==BASIC_imm_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_id_ex_reg_0_0/BASIC_id_ex_reg_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_id_ex_reg_0_0 || ORIG_REF_NAME==BASIC_id_ex_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_alu_0_0/BASIC_alu_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_alu_0_0 || ORIG_REF_NAME==BASIC_alu_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_forwarding_0_0/BASIC_forwarding_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_forwarding_0_0 || ORIG_REF_NAME==BASIC_forwarding_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_forward_mux_0_0/BASIC_forward_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_forward_mux_0_0 || ORIG_REF_NAME==BASIC_forward_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_operand_b_mux_0_0/BASIC_operand_b_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_operand_b_mux_0_0 || ORIG_REF_NAME==BASIC_operand_b_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_operand_a_mux_0_0/BASIC_operand_a_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_operand_a_mux_0_0 || ORIG_REF_NAME==BASIC_operand_a_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_forward_mux_0_1/BASIC_forward_mux_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_forward_mux_0_1 || ORIG_REF_NAME==BASIC_forward_mux_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_branch_0_0/BASIC_branch_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_branch_0_0 || ORIG_REF_NAME==BASIC_branch_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ex_mem_reg_1_0/BASIC_ex_mem_reg_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_ex_mem_reg_1_0 || ORIG_REF_NAME==BASIC_ex_mem_reg_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_mem_stage_0_0/BASIC_mem_stage_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_mem_stage_0_0 || ORIG_REF_NAME==BASIC_mem_stage_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ram_data_1_0/BASIC_ram_data_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_ram_data_1_0 || ORIG_REF_NAME==BASIC_ram_data_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_load_extender_0_0/BASIC_load_extender_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_load_extender_0_0 || ORIG_REF_NAME==BASIC_load_extender_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_xlslice_0_0/BASIC_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_xlslice_0_0 || ORIG_REF_NAME==BASIC_xlslice_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_mem_wb_reg_0_0/BASIC_mem_wb_reg_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_mem_wb_reg_0_0 || ORIG_REF_NAME==BASIC_mem_wb_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_logic_0_0/BASIC_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_logic_0_0 || ORIG_REF_NAME==BASIC_util_vector_logic_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_wb_mux_0_0/BASIC_wb_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_wb_mux_0_0 || ORIG_REF_NAME==BASIC_wb_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_logic_0_1/BASIC_util_vector_logic_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_logic_0_1 || ORIG_REF_NAME==BASIC_util_vector_logic_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_logic_1_0/BASIC_util_vector_logic_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_logic_1_0 || ORIG_REF_NAME==BASIC_util_vector_logic_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_load_use_detection_0_0/BASIC_load_use_detection_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_load_use_detection_0_0 || ORIG_REF_NAME==BASIC_load_use_detection_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_priority_branch_OR_l_0_0/BASIC_priority_branch_OR_l_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_priority_branch_OR_l_0_0 || ORIG_REF_NAME==BASIC_priority_branch_OR_l_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_xlconstant_2_1/BASIC_xlconstant_2_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_xlconstant_2_1 || ORIG_REF_NAME==BASIC_xlconstant_2_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ila_0_0/BASIC_ila_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_ila_0_0 || ORIG_REF_NAME==BASIC_ila_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_vio_0_0/BASIC_vio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_vio_0_0 || ORIG_REF_NAME==BASIC_vio_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_logic_2_0/BASIC_util_vector_logic_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_logic_2_0 || ORIG_REF_NAME==BASIC_util_vector_logic_2_0} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_zynq_ultra_ps_e_0_0/BASIC_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_zynq_ultra_ps_e_0_0/BASIC_zynq_ultra_ps_e_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BASIC_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==BASIC_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_proc_sys_reset_0_0/BASIC_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BASIC_proc_sys_reset_0_0 || ORIG_REF_NAME==BASIC_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_proc_sys_reset_0_0/BASIC_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BASIC_proc_sys_reset_0_0 || ORIG_REF_NAME==BASIC_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_blk_mem_gen_0_0/BASIC_blk_mem_gen_0_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BASIC_ila_0_0 || ORIG_REF_NAME==BASIC_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BASIC_ila_0_0 || ORIG_REF_NAME==BASIC_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ila_0_0/BASIC_ila_0_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_vio_0_0/BASIC_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_vio_0_0 || ORIG_REF_NAME==BASIC_vio_0_0} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_vio_0_0/BASIC_vio_0_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RISCV/RISCV.srcs/sources_1/bd/BASIC/BASIC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BASIC'. Do not add the DONT_TOUCH constraint.
