#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Jun 05 18:49:00 WEST 2026
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 665df9eb1049412aba2015d1f4da0e51 --incr --debug all --relax --mt 8 -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot BASIC_debug_wrapper_behav xil_defaultlib.BASIC_debug_wrapper xil_defaultlib.glbl -log elaborate.log"
xelab -wto 665df9eb1049412aba2015d1f4da0e51 --incr --debug all --relax --mt 8 -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot BASIC_debug_wrapper_behav xil_defaultlib.BASIC_debug_wrapper xil_defaultlib.glbl -log elaborate.log

