#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : BASIC.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu May 28 01:20:31 WEST 2026
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: BASIC.sh [-help]
# usage: BASIC.sh [-lib_map_path]
# usage: BASIC.sh [-noclean_files]
# usage: BASIC.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'BASIC.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "BASIC.sh - Script generated by export_simulation (Vivado v2020.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_pc_unit_0_0/sim/BASIC_pc_unit_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_pc_to_imem_addr_0_0/sim/BASIC_pc_to_imem_addr_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_if_id_reg_0_0/sim/BASIC_if_id_reg_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_decoder_0_0/sim/BASIC_decoder_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_control_0_0/sim/BASIC_control_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_regfile_0_0/sim/BASIC_regfile_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_imm_mux_0_0/sim/BASIC_imm_mux_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_alu_0_0/sim/BASIC_alu_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_forwarding_0_0/sim/BASIC_forwarding_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_forward_mux_0_0/sim/BASIC_forward_mux_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_operand_b_mux_0_0/sim/BASIC_operand_b_mux_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_operand_a_mux_0_0/sim/BASIC_operand_a_mux_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_forward_mux_0_1/sim/BASIC_forward_mux_0_1.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_branch_0_0/sim/BASIC_branch_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_ex_mem_reg_1_0/sim/BASIC_ex_mem_reg_1_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_mem_stage_0_0/sim/BASIC_mem_stage_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_ram_data_1_0/sim/BASIC_ram_data_1_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_mem_wb_reg_0_0/sim/BASIC_mem_wb_reg_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_wb_mux_0_0/sim/BASIC_wb_mux_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_load_use_detection_0_0/sim/BASIC_load_use_detection_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_priority_branch_OR_l_0_0/sim/BASIC_priority_branch_OR_l_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_forward_mux_1_0/sim/BASIC_forward_mux_1_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_regfile_we_gen_0_0/sim/BASIC_regfile_we_gen_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_gpio_0_0/sim/BASIC_gpio_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_uart_tx_0_0/sim/BASIC_uart_tx_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_id_ex_reg_0_1/sim/BASIC_id_ex_reg_0_1.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_branch_predictor_btb_0_0/sim/BASIC_branch_predictor_btb_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_timer_0_0/sim/BASIC_timer_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_mem_bus_registered_0_0/sim/BASIC_mem_bus_registered_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_trap_controller_0_0/sim/BASIC_trap_controller_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_system_decoder_0_0/sim/BASIC_system_decoder_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_csr_file_0_0/sim/BASIC_csr_file_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_privileged_pc_redire_0_0/sim/BASIC_privileged_pc_redire_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_csr_access_unit_0_0/sim/BASIC_csr_access_unit_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_csr_regfile_wb_mux_0_0/sim/BASIC_csr_regfile_wb_mux_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_exception_mux_0_0/sim/BASIC_exception_mux_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_mem_exception_merge_0_0/sim/BASIC_mem_exception_merge_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_util_vector_or_0_1/sim/BASIC_util_vector_or_0_1.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_util_vector_or_0_2/sim/BASIC_util_vector_or_0_2.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_util_vector_and_0_1/sim/BASIC_util_vector_and_0_1.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_util_vector_not_0_1/sim/BASIC_util_vector_not_0_1.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_util_vector_not_0_2/sim/BASIC_util_vector_not_0_2.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_util_vector_and_0_2/sim/BASIC_util_vector_and_0_2.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_util_vector_and_0_3/sim/BASIC_util_vector_and_0_3.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_util_vector_not_0_3/sim/BASIC_util_vector_not_0_3.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_sim_constant_0_3/sim/BASIC_sim_constant_0_3.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_util_vector_and_0_5/sim/BASIC_util_vector_and_0_5.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_util_vector_and_0_6/sim/BASIC_util_vector_and_0_6.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_sim_constant_0_4/sim/BASIC_sim_constant_0_4.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_xlslice_2bit_0_0/sim/BASIC_xlslice_2bit_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_xlconcat_8_0_0/sim/BASIC_xlconcat_8_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_rom_memory_0_0/sim/BASIC_rom_memory_0_0.v" \
    "$ref_dir/../../../bd/BASIC/ip/BASIC_sim_constant_0_5/sim/BASIC_sim_constant_0_5.v" \
    "$ref_dir/../../../bd/BASIC/sim/BASIC.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.BASIC xil_defaultlib.glbl -o BASIC_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./BASIC_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./BASIC.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/OLD/RISCV_FOR_COCOTB/RISCV.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key BASIC_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc BASIC_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./BASIC.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: BASIC.sh [-help]\n\
Usage: BASIC.sh [-lib_map_path]\n\
Usage: BASIC.sh [-reset_run]\n\
Usage: BASIC.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
