#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Mar 12 01:04:08 WET 2026
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim Section_debug_wrapper_behav -key {Behavioral:sim_1:Functional:Section_debug_wrapper} -tclbatch Section_debug_wrapper.tcl -protoinst "protoinst_files/Section_debug.protoinst" -view /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/simulation/tb_cpu_behav_iROM.wcfg -log simulate.log"
xsim Section_debug_wrapper_behav -key {Behavioral:sim_1:Functional:Section_debug_wrapper} -tclbatch Section_debug_wrapper.tcl -protoinst "protoinst_files/Section_debug.protoinst" -view /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/simulation/tb_cpu_behav_iROM.wcfg -log simulate.log

