#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Apr 20 21:03:09 WEST 2026
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim RISCV_SystemVerilog_wrapper_behav -key {Behavioral:sim_1:Functional:RISCV_SystemVerilog_wrapper} -tclbatch RISCV_SystemVerilog_wrapper.tcl -protoinst "protoinst_files/RISCV_SystemVerilog.protoinst" -view /media/steckler/xilinx_linux/RISCV_ZYNQ/1/RVI20U32/RVI20U32/CPU_V1/simulation/tb_cpu_behav_iROM.wcfg -log simulate.log"
xsim RISCV_SystemVerilog_wrapper_behav -key {Behavioral:sim_1:Functional:RISCV_SystemVerilog_wrapper} -tclbatch RISCV_SystemVerilog_wrapper.tcl -protoinst "protoinst_files/RISCV_SystemVerilog.protoinst" -view /media/steckler/xilinx_linux/RISCV_ZYNQ/1/RVI20U32/RVI20U32/CPU_V1/simulation/tb_cpu_behav_iROM.wcfg -log simulate.log

