# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/RV32_IF_EX.bd
# Block Designs: The module: 'RV32_IF_EX' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_if_id_reg_0_0/RV32_IF_EX_if_id_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_if_id_reg_0_0 || ORIG_REF_NAME==RV32_IF_EX_if_id_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_pc_to_imem_addr_0_0/RV32_IF_EX_pc_to_imem_addr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_pc_to_imem_addr_0_0 || ORIG_REF_NAME==RV32_IF_EX_pc_to_imem_addr_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_pc_unit_0_0/RV32_IF_EX_pc_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_pc_unit_0_0 || ORIG_REF_NAME==RV32_IF_EX_pc_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_rom_memory_0_0/RV32_IF_EX_rom_memory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_rom_memory_0_0 || ORIG_REF_NAME==RV32_IF_EX_rom_memory_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_sim_constant_0_0/RV32_IF_EX_sim_constant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_sim_constant_0_0 || ORIG_REF_NAME==RV32_IF_EX_sim_constant_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_control_0_0/RV32_IF_EX_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_control_0_0 || ORIG_REF_NAME==RV32_IF_EX_control_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_decoder_0_0/RV32_IF_EX_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_decoder_0_0 || ORIG_REF_NAME==RV32_IF_EX_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_id_ex_reg_0_0/RV32_IF_EX_id_ex_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_id_ex_reg_0_0 || ORIG_REF_NAME==RV32_IF_EX_id_ex_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_imm_mux_0_0/RV32_IF_EX_imm_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_imm_mux_0_0 || ORIG_REF_NAME==RV32_IF_EX_imm_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_regfile_0_0/RV32_IF_EX_regfile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_regfile_0_0 || ORIG_REF_NAME==RV32_IF_EX_regfile_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_sim_constant_0_1/RV32_IF_EX_sim_constant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_sim_constant_0_1 || ORIG_REF_NAME==RV32_IF_EX_sim_constant_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_sim_constant_1_0/RV32_IF_EX_sim_constant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_sim_constant_1_0 || ORIG_REF_NAME==RV32_IF_EX_sim_constant_1_0} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/RV32_IF_EX_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RV32_IF_EX'. Do not add the DONT_TOUCH constraint.

# Block Designs: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/RV32_IF_EX.bd
# Block Designs: The module: 'RV32_IF_EX' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_if_id_reg_0_0/RV32_IF_EX_if_id_reg_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_if_id_reg_0_0 || ORIG_REF_NAME==RV32_IF_EX_if_id_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_pc_to_imem_addr_0_0/RV32_IF_EX_pc_to_imem_addr_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_pc_to_imem_addr_0_0 || ORIG_REF_NAME==RV32_IF_EX_pc_to_imem_addr_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_pc_unit_0_0/RV32_IF_EX_pc_unit_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_pc_unit_0_0 || ORIG_REF_NAME==RV32_IF_EX_pc_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_rom_memory_0_0/RV32_IF_EX_rom_memory_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_rom_memory_0_0 || ORIG_REF_NAME==RV32_IF_EX_rom_memory_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_sim_constant_0_0/RV32_IF_EX_sim_constant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_sim_constant_0_0 || ORIG_REF_NAME==RV32_IF_EX_sim_constant_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_control_0_0/RV32_IF_EX_control_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_control_0_0 || ORIG_REF_NAME==RV32_IF_EX_control_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_decoder_0_0/RV32_IF_EX_decoder_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_decoder_0_0 || ORIG_REF_NAME==RV32_IF_EX_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_id_ex_reg_0_0/RV32_IF_EX_id_ex_reg_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_id_ex_reg_0_0 || ORIG_REF_NAME==RV32_IF_EX_id_ex_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_imm_mux_0_0/RV32_IF_EX_imm_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_imm_mux_0_0 || ORIG_REF_NAME==RV32_IF_EX_imm_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_regfile_0_0/RV32_IF_EX_regfile_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_regfile_0_0 || ORIG_REF_NAME==RV32_IF_EX_regfile_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_sim_constant_0_1/RV32_IF_EX_sim_constant_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_sim_constant_0_1 || ORIG_REF_NAME==RV32_IF_EX_sim_constant_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/ip/RV32_IF_EX_sim_constant_1_0/RV32_IF_EX_sim_constant_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32_IF_EX_sim_constant_1_0 || ORIG_REF_NAME==RV32_IF_EX_sim_constant_1_0} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RV32I_RELESED/RV32/RV32.srcs/sources_1/bd/RV32_IF_EX/RV32_IF_EX_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RV32_IF_EX'. Do not add the DONT_TOUCH constraint.
