#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : Debug_2.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun Apr 19 22:47:22 WEST 2026
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: Debug_2.sh [-help]
# usage: Debug_2.sh [-lib_map_path]
# usage: Debug_2.sh [-noclean_files]
# usage: Debug_2.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'Debug_2.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib util_vector_logic_v2_0_1 xlconstant_v1_1_7 blk_mem_gen_v8_4_4 xlslice_v1_0_2 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 axi_infrastructure_v1_1_0 axi_vip_v1_1_7 zynq_ultra_ps_e_vip_v1_0_7)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "Debug_2.sh - Script generated by export_simulation (Vivado v2020.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_forwarding_uni_0_0/sim/Debug_2_rv32i_forwarding_uni_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_branch_unit_wr_0_0/sim/Debug_2_rv32i_branch_unit_wr_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_alu_wrapper_0_0/sim/Debug_2_rv32i_alu_wrapper_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_operand_b_mux_0_0/sim/Debug_2_rv32i_operand_b_mux_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_ex_mem_reg_wra_0_0/sim/Debug_2_rv32i_ex_mem_reg_wra_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_operand_a_mux_0_0/sim/Debug_2_rv32i_operand_a_mux_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_forward_mux_wr_0_0/sim/Debug_2_rv32i_forward_mux_wr_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_forward_mux_wr_1_0/sim/Debug_2_rv32i_forward_mux_wr_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_util_vector_logic_4_0/sim/Debug_2_util_vector_logic_4_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_imm_mux_wrapper_0_0/sim/Debug_2_rv32i_imm_mux_wrapper_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_regfile_wrapper_0_0/sim/Debug_2_rv32i_regfile_wrapper_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_id_ex_reg_wrap_0_0/sim/Debug_2_rv32i_id_ex_reg_wrap_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_control_full_w_0_0/sim/Debug_2_rv32i_control_full_w_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_decoder_wrapper_0_0/sim/Debug_2_rv32i_decoder_wrapper_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_pc_to_rom_addr_wrapp_0_1/sim/Debug_2_pc_to_rom_addr_wrapp_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_xlconstant_1_1/sim/Debug_2_xlconstant_1_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_blk_mem_gen_0_1/sim/Debug_2_blk_mem_gen_0_1.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_pc_unit_wrapper_0_1/sim/Debug_2_pc_unit_wrapper_0_1.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_if_id_reg_wrap_0_1/sim/Debug_2_rv32i_if_id_reg_wrap_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_xlslice_0_0/sim/Debug_2_xlslice_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_ram_datav_wrap_0_0/sim/Debug_2_rv32i_ram_datav_wrap_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_load_extender_0_0/sim/Debug_2_rv32i_load_extender_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_xlconstant_1_2/sim/Debug_2_xlconstant_1_2.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_mem_stage_wrap_0_0/sim/Debug_2_rv32i_mem_stage_wrap_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_mem_wb_reg_wra_0_0/sim/Debug_2_rv32i_mem_wb_reg_wra_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_xlconstant_0_1/sim/Debug_2_xlconstant_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_proc_sys_reset_0_1/sim/Debug_2_proc_sys_reset_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_util_vector_logic_0_1/sim/Debug_2_util_vector_logic_0_1.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_rv32i_wb_mux_wrapper_0_0/sim/Debug_2_rv32i_wb_mux_wrapper_0_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_util_vector_logic_2_0/sim/Debug_2_util_vector_logic_2_0.v" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_vio_0_1/sim/Debug_2_vio_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ce6c/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../CPU_V1.srcs/sources_1/bd/Debug_2/ipshared/46fd/hdl" +incdir+"/media/steckler/xilinx_linux/vitis_2020.1/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Debug_2/ip/Debug_2_zynq_ultra_ps_e_1_1/sim/Debug_2_zynq_ultra_ps_e_1_1_vip_wrapper.v" \
    "$ref_dir/../../../bd/Debug_2/sim/Debug_2.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.Debug_2 xil_defaultlib.glbl -o Debug_2_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./Debug_2_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./Debug_2.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key Debug_2_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc Debug_2_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./Debug_2.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: Debug_2.sh [-help]\n\
Usage: Debug_2.sh [-lib_map_path]\n\
Usage: Debug_2.sh [-reset_run]\n\
Usage: Debug_2.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
