# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/debug.bd
# Block Designs: The module: 'debug' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_xlconstant_0_0/debug_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_xlconstant_0_0 || ORIG_REF_NAME==debug_xlconstant_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_proc_sys_reset_0_0/debug_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_proc_sys_reset_0_0 || ORIG_REF_NAME==debug_proc_sys_reset_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_util_vector_logic_0_1/debug_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_util_vector_logic_0_1 || ORIG_REF_NAME==debug_util_vector_logic_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_vio_0_0/debug_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_vio_0_0 || ORIG_REF_NAME==debug_vio_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_zynq_ultra_ps_e_1_0/debug_zynq_ultra_ps_e_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_zynq_ultra_ps_e_1_0 || ORIG_REF_NAME==debug_zynq_ultra_ps_e_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_pc_unit_wrapper_0_1/debug_pc_unit_wrapper_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_pc_unit_wrapper_0_1 || ORIG_REF_NAME==debug_pc_unit_wrapper_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_blk_mem_gen_0_1/debug_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_blk_mem_gen_0_1 || ORIG_REF_NAME==debug_blk_mem_gen_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_pc_to_rom_addr_wrapp_0_1/debug_pc_to_rom_addr_wrapp_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_pc_to_rom_addr_wrapp_0_1 || ORIG_REF_NAME==debug_pc_to_rom_addr_wrapp_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_xlconstant_1_1/debug_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_xlconstant_1_1 || ORIG_REF_NAME==debug_xlconstant_1_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_if_id_reg_wrap_0_1/debug_rv32i_if_id_reg_wrap_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_if_id_reg_wrap_0_1 || ORIG_REF_NAME==debug_rv32i_if_id_reg_wrap_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_control_full_w_0_0/debug_rv32i_control_full_w_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_control_full_w_0_0 || ORIG_REF_NAME==debug_rv32i_control_full_w_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_decoder_wrapper_0_0/debug_rv32i_decoder_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_decoder_wrapper_0_0 || ORIG_REF_NAME==debug_rv32i_decoder_wrapper_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_hazard_detecti_0_0/debug_rv32i_hazard_detecti_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_hazard_detecti_0_0 || ORIG_REF_NAME==debug_rv32i_hazard_detecti_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_id_ex_reg_wrap_0_0/debug_rv32i_id_ex_reg_wrap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_id_ex_reg_wrap_0_0 || ORIG_REF_NAME==debug_rv32i_id_ex_reg_wrap_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_imm_mux_wrapper_0_0/debug_rv32i_imm_mux_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_imm_mux_wrapper_0_0 || ORIG_REF_NAME==debug_rv32i_imm_mux_wrapper_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_regfile_wrapper_0_0/debug_rv32i_regfile_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_regfile_wrapper_0_0 || ORIG_REF_NAME==debug_rv32i_regfile_wrapper_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_xlconstant_1_3/debug_xlconstant_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_xlconstant_1_3 || ORIG_REF_NAME==debug_xlconstant_1_3} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_alu_wrapper_0_0/debug_rv32i_alu_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_alu_wrapper_0_0 || ORIG_REF_NAME==debug_rv32i_alu_wrapper_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_branch_unit_wr_0_0/debug_rv32i_branch_unit_wr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_branch_unit_wr_0_0 || ORIG_REF_NAME==debug_rv32i_branch_unit_wr_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_ex_mem_reg_wra_0_0/debug_rv32i_ex_mem_reg_wra_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_ex_mem_reg_wra_0_0 || ORIG_REF_NAME==debug_rv32i_ex_mem_reg_wra_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_operand_a_mux_0_0/debug_rv32i_operand_a_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_operand_a_mux_0_0 || ORIG_REF_NAME==debug_rv32i_operand_a_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_operand_b_mux_0_0/debug_rv32i_operand_b_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_operand_b_mux_0_0 || ORIG_REF_NAME==debug_rv32i_operand_b_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_forward_mux_wr_0_0/debug_rv32i_forward_mux_wr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_forward_mux_wr_0_0 || ORIG_REF_NAME==debug_rv32i_forward_mux_wr_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_forward_mux_wr_1_0/debug_rv32i_forward_mux_wr_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_forward_mux_wr_1_0 || ORIG_REF_NAME==debug_rv32i_forward_mux_wr_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_forwarding_uni_0_0/debug_rv32i_forwarding_uni_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_forwarding_uni_0_0 || ORIG_REF_NAME==debug_rv32i_forwarding_uni_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_util_vector_logic_4_0/debug_util_vector_logic_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_util_vector_logic_4_0 || ORIG_REF_NAME==debug_util_vector_logic_4_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_xlslice_0_0/debug_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_xlslice_0_0 || ORIG_REF_NAME==debug_xlslice_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_ram_datav_wrap_0_0/debug_rv32i_ram_datav_wrap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_ram_datav_wrap_0_0 || ORIG_REF_NAME==debug_rv32i_ram_datav_wrap_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_load_extender_0_0/debug_rv32i_load_extender_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_load_extender_0_0 || ORIG_REF_NAME==debug_rv32i_load_extender_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_xlconstant_1_4/debug_xlconstant_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_xlconstant_1_4 || ORIG_REF_NAME==debug_xlconstant_1_4} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_mem_stage_wrap_0_0/debug_rv32i_mem_stage_wrap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_mem_stage_wrap_0_0 || ORIG_REF_NAME==debug_rv32i_mem_stage_wrap_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_mem_wb_reg_wra_0_0/debug_rv32i_mem_wb_reg_wra_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_mem_wb_reg_wra_0_0 || ORIG_REF_NAME==debug_rv32i_mem_wb_reg_wra_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_wb_mux_wrapper_0_0/debug_rv32i_wb_mux_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_wb_mux_wrapper_0_0 || ORIG_REF_NAME==debug_rv32i_wb_mux_wrapper_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_util_vector_logic_2_0/debug_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_util_vector_logic_2_0 || ORIG_REF_NAME==debug_util_vector_logic_2_0} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_proc_sys_reset_0_0/debug_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==debug_proc_sys_reset_0_0 || ORIG_REF_NAME==debug_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_proc_sys_reset_0_0/debug_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==debug_proc_sys_reset_0_0 || ORIG_REF_NAME==debug_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_vio_0_0/debug_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_vio_0_0 || ORIG_REF_NAME==debug_vio_0_0} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_zynq_ultra_ps_e_1_0/debug_zynq_ultra_ps_e_1_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_zynq_ultra_ps_e_1_0/debug_zynq_ultra_ps_e_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==debug_zynq_ultra_ps_e_1_0 || ORIG_REF_NAME==debug_zynq_ultra_ps_e_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_blk_mem_gen_0_1/debug_blk_mem_gen_0_1_ooc.xdc

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/debug_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug'. Do not add the DONT_TOUCH constraint.

# Block Designs: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/debug.bd
# Block Designs: The module: 'debug' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_xlconstant_0_0/debug_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_xlconstant_0_0 || ORIG_REF_NAME==debug_xlconstant_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_proc_sys_reset_0_0/debug_proc_sys_reset_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_proc_sys_reset_0_0 || ORIG_REF_NAME==debug_proc_sys_reset_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_util_vector_logic_0_1/debug_util_vector_logic_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_util_vector_logic_0_1 || ORIG_REF_NAME==debug_util_vector_logic_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_vio_0_0/debug_vio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_vio_0_0 || ORIG_REF_NAME==debug_vio_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_zynq_ultra_ps_e_1_0/debug_zynq_ultra_ps_e_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_zynq_ultra_ps_e_1_0 || ORIG_REF_NAME==debug_zynq_ultra_ps_e_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_pc_unit_wrapper_0_1/debug_pc_unit_wrapper_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_pc_unit_wrapper_0_1 || ORIG_REF_NAME==debug_pc_unit_wrapper_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_blk_mem_gen_0_1/debug_blk_mem_gen_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_blk_mem_gen_0_1 || ORIG_REF_NAME==debug_blk_mem_gen_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_pc_to_rom_addr_wrapp_0_1/debug_pc_to_rom_addr_wrapp_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_pc_to_rom_addr_wrapp_0_1 || ORIG_REF_NAME==debug_pc_to_rom_addr_wrapp_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_xlconstant_1_1/debug_xlconstant_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_xlconstant_1_1 || ORIG_REF_NAME==debug_xlconstant_1_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_if_id_reg_wrap_0_1/debug_rv32i_if_id_reg_wrap_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_if_id_reg_wrap_0_1 || ORIG_REF_NAME==debug_rv32i_if_id_reg_wrap_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_control_full_w_0_0/debug_rv32i_control_full_w_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_control_full_w_0_0 || ORIG_REF_NAME==debug_rv32i_control_full_w_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_decoder_wrapper_0_0/debug_rv32i_decoder_wrapper_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_decoder_wrapper_0_0 || ORIG_REF_NAME==debug_rv32i_decoder_wrapper_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_hazard_detecti_0_0/debug_rv32i_hazard_detecti_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_hazard_detecti_0_0 || ORIG_REF_NAME==debug_rv32i_hazard_detecti_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_id_ex_reg_wrap_0_0/debug_rv32i_id_ex_reg_wrap_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_id_ex_reg_wrap_0_0 || ORIG_REF_NAME==debug_rv32i_id_ex_reg_wrap_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_imm_mux_wrapper_0_0/debug_rv32i_imm_mux_wrapper_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_imm_mux_wrapper_0_0 || ORIG_REF_NAME==debug_rv32i_imm_mux_wrapper_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_regfile_wrapper_0_0/debug_rv32i_regfile_wrapper_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_regfile_wrapper_0_0 || ORIG_REF_NAME==debug_rv32i_regfile_wrapper_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_xlconstant_1_3/debug_xlconstant_1_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_xlconstant_1_3 || ORIG_REF_NAME==debug_xlconstant_1_3} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_alu_wrapper_0_0/debug_rv32i_alu_wrapper_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_alu_wrapper_0_0 || ORIG_REF_NAME==debug_rv32i_alu_wrapper_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_branch_unit_wr_0_0/debug_rv32i_branch_unit_wr_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_branch_unit_wr_0_0 || ORIG_REF_NAME==debug_rv32i_branch_unit_wr_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_ex_mem_reg_wra_0_0/debug_rv32i_ex_mem_reg_wra_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_ex_mem_reg_wra_0_0 || ORIG_REF_NAME==debug_rv32i_ex_mem_reg_wra_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_operand_a_mux_0_0/debug_rv32i_operand_a_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_operand_a_mux_0_0 || ORIG_REF_NAME==debug_rv32i_operand_a_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_operand_b_mux_0_0/debug_rv32i_operand_b_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_operand_b_mux_0_0 || ORIG_REF_NAME==debug_rv32i_operand_b_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_forward_mux_wr_0_0/debug_rv32i_forward_mux_wr_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_forward_mux_wr_0_0 || ORIG_REF_NAME==debug_rv32i_forward_mux_wr_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_forward_mux_wr_1_0/debug_rv32i_forward_mux_wr_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_forward_mux_wr_1_0 || ORIG_REF_NAME==debug_rv32i_forward_mux_wr_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_forwarding_uni_0_0/debug_rv32i_forwarding_uni_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_forwarding_uni_0_0 || ORIG_REF_NAME==debug_rv32i_forwarding_uni_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_util_vector_logic_4_0/debug_util_vector_logic_4_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_util_vector_logic_4_0 || ORIG_REF_NAME==debug_util_vector_logic_4_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_xlslice_0_0/debug_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_xlslice_0_0 || ORIG_REF_NAME==debug_xlslice_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_ram_datav_wrap_0_0/debug_rv32i_ram_datav_wrap_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_ram_datav_wrap_0_0 || ORIG_REF_NAME==debug_rv32i_ram_datav_wrap_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_load_extender_0_0/debug_rv32i_load_extender_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_load_extender_0_0 || ORIG_REF_NAME==debug_rv32i_load_extender_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_xlconstant_1_4/debug_xlconstant_1_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_xlconstant_1_4 || ORIG_REF_NAME==debug_xlconstant_1_4} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_mem_stage_wrap_0_0/debug_rv32i_mem_stage_wrap_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_mem_stage_wrap_0_0 || ORIG_REF_NAME==debug_rv32i_mem_stage_wrap_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_mem_wb_reg_wra_0_0/debug_rv32i_mem_wb_reg_wra_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_mem_wb_reg_wra_0_0 || ORIG_REF_NAME==debug_rv32i_mem_wb_reg_wra_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_rv32i_wb_mux_wrapper_0_0/debug_rv32i_wb_mux_wrapper_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_rv32i_wb_mux_wrapper_0_0 || ORIG_REF_NAME==debug_rv32i_wb_mux_wrapper_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_util_vector_logic_2_0/debug_util_vector_logic_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_util_vector_logic_2_0 || ORIG_REF_NAME==debug_util_vector_logic_2_0} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_proc_sys_reset_0_0/debug_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==debug_proc_sys_reset_0_0 || ORIG_REF_NAME==debug_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_proc_sys_reset_0_0/debug_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==debug_proc_sys_reset_0_0 || ORIG_REF_NAME==debug_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_vio_0_0/debug_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==debug_vio_0_0 || ORIG_REF_NAME==debug_vio_0_0} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_zynq_ultra_ps_e_1_0/debug_zynq_ultra_ps_e_1_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_zynq_ultra_ps_e_1_0/debug_zynq_ultra_ps_e_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==debug_zynq_ultra_ps_e_1_0 || ORIG_REF_NAME==debug_zynq_ultra_ps_e_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/ip/debug_blk_mem_gen_0_1/debug_blk_mem_gen_0_1_ooc.xdc

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/Con_problema_plus4_no_escribe/RVI20U32/RVI20U32/CPU_V1/CPU_V1.srcs/sources_1/bd/debug/debug_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug'. Do not add the DONT_TOUCH constraint.
