# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/BASIC.bd
# Block Designs: The module: 'BASIC' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_pc_unit_0_0/BASIC_pc_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_pc_unit_0_0 || ORIG_REF_NAME==BASIC_pc_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_pc_to_imem_addr_0_0/BASIC_pc_to_imem_addr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_pc_to_imem_addr_0_0 || ORIG_REF_NAME==BASIC_pc_to_imem_addr_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_if_id_reg_0_0/BASIC_if_id_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_if_id_reg_0_0 || ORIG_REF_NAME==BASIC_if_id_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_decoder_0_0/BASIC_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_decoder_0_0 || ORIG_REF_NAME==BASIC_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_control_0_0/BASIC_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_control_0_0 || ORIG_REF_NAME==BASIC_control_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_regfile_0_0/BASIC_regfile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_regfile_0_0 || ORIG_REF_NAME==BASIC_regfile_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_imm_mux_0_0/BASIC_imm_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_imm_mux_0_0 || ORIG_REF_NAME==BASIC_imm_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_alu_0_0/BASIC_alu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_alu_0_0 || ORIG_REF_NAME==BASIC_alu_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_forwarding_0_0/BASIC_forwarding_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_forwarding_0_0 || ORIG_REF_NAME==BASIC_forwarding_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_forward_mux_0_0/BASIC_forward_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_forward_mux_0_0 || ORIG_REF_NAME==BASIC_forward_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_operand_b_mux_0_0/BASIC_operand_b_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_operand_b_mux_0_0 || ORIG_REF_NAME==BASIC_operand_b_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_operand_a_mux_0_0/BASIC_operand_a_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_operand_a_mux_0_0 || ORIG_REF_NAME==BASIC_operand_a_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_forward_mux_0_1/BASIC_forward_mux_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_forward_mux_0_1 || ORIG_REF_NAME==BASIC_forward_mux_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_branch_0_0/BASIC_branch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_branch_0_0 || ORIG_REF_NAME==BASIC_branch_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ex_mem_reg_1_0/BASIC_ex_mem_reg_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_ex_mem_reg_1_0 || ORIG_REF_NAME==BASIC_ex_mem_reg_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_mem_stage_0_0/BASIC_mem_stage_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_mem_stage_0_0 || ORIG_REF_NAME==BASIC_mem_stage_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ram_data_1_0/BASIC_ram_data_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_ram_data_1_0 || ORIG_REF_NAME==BASIC_ram_data_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_mem_wb_reg_0_0/BASIC_mem_wb_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_mem_wb_reg_0_0 || ORIG_REF_NAME==BASIC_mem_wb_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_wb_mux_0_0/BASIC_wb_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_wb_mux_0_0 || ORIG_REF_NAME==BASIC_wb_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_load_use_detection_0_0/BASIC_load_use_detection_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_load_use_detection_0_0 || ORIG_REF_NAME==BASIC_load_use_detection_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_priority_branch_OR_l_0_0/BASIC_priority_branch_OR_l_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_priority_branch_OR_l_0_0 || ORIG_REF_NAME==BASIC_priority_branch_OR_l_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_forward_mux_1_0/BASIC_forward_mux_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_forward_mux_1_0 || ORIG_REF_NAME==BASIC_forward_mux_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_regfile_we_gen_0_0/BASIC_regfile_we_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_regfile_we_gen_0_0 || ORIG_REF_NAME==BASIC_regfile_we_gen_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_gpio_0_0/BASIC_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_gpio_0_0 || ORIG_REF_NAME==BASIC_gpio_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_uart_tx_0_0/BASIC_uart_tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_uart_tx_0_0 || ORIG_REF_NAME==BASIC_uart_tx_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_id_ex_reg_0_1/BASIC_id_ex_reg_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_id_ex_reg_0_1 || ORIG_REF_NAME==BASIC_id_ex_reg_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_branch_predictor_btb_0_0/BASIC_branch_predictor_btb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_branch_predictor_btb_0_0 || ORIG_REF_NAME==BASIC_branch_predictor_btb_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_timer_0_0/BASIC_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_timer_0_0 || ORIG_REF_NAME==BASIC_timer_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_mem_bus_registered_0_0/BASIC_mem_bus_registered_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_mem_bus_registered_0_0 || ORIG_REF_NAME==BASIC_mem_bus_registered_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_trap_controller_0_0/BASIC_trap_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_trap_controller_0_0 || ORIG_REF_NAME==BASIC_trap_controller_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_system_decoder_0_0/BASIC_system_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_system_decoder_0_0 || ORIG_REF_NAME==BASIC_system_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_csr_file_0_0/BASIC_csr_file_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_csr_file_0_0 || ORIG_REF_NAME==BASIC_csr_file_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_privileged_pc_redire_0_0/BASIC_privileged_pc_redire_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_privileged_pc_redire_0_0 || ORIG_REF_NAME==BASIC_privileged_pc_redire_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_csr_access_unit_0_0/BASIC_csr_access_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_csr_access_unit_0_0 || ORIG_REF_NAME==BASIC_csr_access_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_csr_regfile_wb_mux_0_0/BASIC_csr_regfile_wb_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_csr_regfile_wb_mux_0_0 || ORIG_REF_NAME==BASIC_csr_regfile_wb_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_exception_mux_0_0/BASIC_exception_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_exception_mux_0_0 || ORIG_REF_NAME==BASIC_exception_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_mem_exception_merge_0_0/BASIC_mem_exception_merge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_mem_exception_merge_0_0 || ORIG_REF_NAME==BASIC_mem_exception_merge_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_or_0_1/BASIC_util_vector_or_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_or_0_1 || ORIG_REF_NAME==BASIC_util_vector_or_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_or_0_2/BASIC_util_vector_or_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_or_0_2 || ORIG_REF_NAME==BASIC_util_vector_or_0_2} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_and_0_1/BASIC_util_vector_and_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_and_0_1 || ORIG_REF_NAME==BASIC_util_vector_and_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_not_0_1/BASIC_util_vector_not_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_not_0_1 || ORIG_REF_NAME==BASIC_util_vector_not_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_not_0_2/BASIC_util_vector_not_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_not_0_2 || ORIG_REF_NAME==BASIC_util_vector_not_0_2} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_and_0_2/BASIC_util_vector_and_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_and_0_2 || ORIG_REF_NAME==BASIC_util_vector_and_0_2} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_and_0_3/BASIC_util_vector_and_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_and_0_3 || ORIG_REF_NAME==BASIC_util_vector_and_0_3} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_not_0_3/BASIC_util_vector_not_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_not_0_3 || ORIG_REF_NAME==BASIC_util_vector_not_0_3} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_sim_constant_0_3/BASIC_sim_constant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_sim_constant_0_3 || ORIG_REF_NAME==BASIC_sim_constant_0_3} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_and_0_5/BASIC_util_vector_and_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_and_0_5 || ORIG_REF_NAME==BASIC_util_vector_and_0_5} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_and_0_6/BASIC_util_vector_and_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_and_0_6 || ORIG_REF_NAME==BASIC_util_vector_and_0_6} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_sim_constant_0_4/BASIC_sim_constant_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_sim_constant_0_4 || ORIG_REF_NAME==BASIC_sim_constant_0_4} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_xlslice_2bit_0_0/BASIC_xlslice_2bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_xlslice_2bit_0_0 || ORIG_REF_NAME==BASIC_xlslice_2bit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_xlconcat_8_0_0/BASIC_xlconcat_8_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_xlconcat_8_0_0 || ORIG_REF_NAME==BASIC_xlconcat_8_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_rom_memory_0_0/BASIC_rom_memory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_rom_memory_0_0 || ORIG_REF_NAME==BASIC_rom_memory_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_sim_constant_0_5/BASIC_sim_constant_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_sim_constant_0_5 || ORIG_REF_NAME==BASIC_sim_constant_0_5} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/BASIC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BASIC'. Do not add the DONT_TOUCH constraint.

# Block Designs: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/BASIC.bd
# Block Designs: The module: 'BASIC' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_pc_unit_0_0/BASIC_pc_unit_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_pc_unit_0_0 || ORIG_REF_NAME==BASIC_pc_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_pc_to_imem_addr_0_0/BASIC_pc_to_imem_addr_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_pc_to_imem_addr_0_0 || ORIG_REF_NAME==BASIC_pc_to_imem_addr_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_if_id_reg_0_0/BASIC_if_id_reg_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_if_id_reg_0_0 || ORIG_REF_NAME==BASIC_if_id_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_decoder_0_0/BASIC_decoder_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_decoder_0_0 || ORIG_REF_NAME==BASIC_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_control_0_0/BASIC_control_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_control_0_0 || ORIG_REF_NAME==BASIC_control_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_regfile_0_0/BASIC_regfile_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_regfile_0_0 || ORIG_REF_NAME==BASIC_regfile_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_imm_mux_0_0/BASIC_imm_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_imm_mux_0_0 || ORIG_REF_NAME==BASIC_imm_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_alu_0_0/BASIC_alu_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_alu_0_0 || ORIG_REF_NAME==BASIC_alu_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_forwarding_0_0/BASIC_forwarding_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_forwarding_0_0 || ORIG_REF_NAME==BASIC_forwarding_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_forward_mux_0_0/BASIC_forward_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_forward_mux_0_0 || ORIG_REF_NAME==BASIC_forward_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_operand_b_mux_0_0/BASIC_operand_b_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_operand_b_mux_0_0 || ORIG_REF_NAME==BASIC_operand_b_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_operand_a_mux_0_0/BASIC_operand_a_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_operand_a_mux_0_0 || ORIG_REF_NAME==BASIC_operand_a_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_forward_mux_0_1/BASIC_forward_mux_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_forward_mux_0_1 || ORIG_REF_NAME==BASIC_forward_mux_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_branch_0_0/BASIC_branch_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_branch_0_0 || ORIG_REF_NAME==BASIC_branch_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ex_mem_reg_1_0/BASIC_ex_mem_reg_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_ex_mem_reg_1_0 || ORIG_REF_NAME==BASIC_ex_mem_reg_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_mem_stage_0_0/BASIC_mem_stage_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_mem_stage_0_0 || ORIG_REF_NAME==BASIC_mem_stage_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_ram_data_1_0/BASIC_ram_data_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_ram_data_1_0 || ORIG_REF_NAME==BASIC_ram_data_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_mem_wb_reg_0_0/BASIC_mem_wb_reg_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_mem_wb_reg_0_0 || ORIG_REF_NAME==BASIC_mem_wb_reg_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_wb_mux_0_0/BASIC_wb_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_wb_mux_0_0 || ORIG_REF_NAME==BASIC_wb_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_load_use_detection_0_0/BASIC_load_use_detection_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_load_use_detection_0_0 || ORIG_REF_NAME==BASIC_load_use_detection_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_priority_branch_OR_l_0_0/BASIC_priority_branch_OR_l_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_priority_branch_OR_l_0_0 || ORIG_REF_NAME==BASIC_priority_branch_OR_l_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_forward_mux_1_0/BASIC_forward_mux_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_forward_mux_1_0 || ORIG_REF_NAME==BASIC_forward_mux_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_regfile_we_gen_0_0/BASIC_regfile_we_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_regfile_we_gen_0_0 || ORIG_REF_NAME==BASIC_regfile_we_gen_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_gpio_0_0/BASIC_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_gpio_0_0 || ORIG_REF_NAME==BASIC_gpio_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_uart_tx_0_0/BASIC_uart_tx_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_uart_tx_0_0 || ORIG_REF_NAME==BASIC_uart_tx_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_id_ex_reg_0_1/BASIC_id_ex_reg_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_id_ex_reg_0_1 || ORIG_REF_NAME==BASIC_id_ex_reg_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_branch_predictor_btb_0_0/BASIC_branch_predictor_btb_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_branch_predictor_btb_0_0 || ORIG_REF_NAME==BASIC_branch_predictor_btb_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_timer_0_0/BASIC_timer_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_timer_0_0 || ORIG_REF_NAME==BASIC_timer_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_mem_bus_registered_0_0/BASIC_mem_bus_registered_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_mem_bus_registered_0_0 || ORIG_REF_NAME==BASIC_mem_bus_registered_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_trap_controller_0_0/BASIC_trap_controller_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_trap_controller_0_0 || ORIG_REF_NAME==BASIC_trap_controller_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_system_decoder_0_0/BASIC_system_decoder_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_system_decoder_0_0 || ORIG_REF_NAME==BASIC_system_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_csr_file_0_0/BASIC_csr_file_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_csr_file_0_0 || ORIG_REF_NAME==BASIC_csr_file_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_privileged_pc_redire_0_0/BASIC_privileged_pc_redire_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_privileged_pc_redire_0_0 || ORIG_REF_NAME==BASIC_privileged_pc_redire_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_csr_access_unit_0_0/BASIC_csr_access_unit_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_csr_access_unit_0_0 || ORIG_REF_NAME==BASIC_csr_access_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_csr_regfile_wb_mux_0_0/BASIC_csr_regfile_wb_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_csr_regfile_wb_mux_0_0 || ORIG_REF_NAME==BASIC_csr_regfile_wb_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_exception_mux_0_0/BASIC_exception_mux_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_exception_mux_0_0 || ORIG_REF_NAME==BASIC_exception_mux_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_mem_exception_merge_0_0/BASIC_mem_exception_merge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_mem_exception_merge_0_0 || ORIG_REF_NAME==BASIC_mem_exception_merge_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_or_0_1/BASIC_util_vector_or_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_or_0_1 || ORIG_REF_NAME==BASIC_util_vector_or_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_or_0_2/BASIC_util_vector_or_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_or_0_2 || ORIG_REF_NAME==BASIC_util_vector_or_0_2} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_and_0_1/BASIC_util_vector_and_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_and_0_1 || ORIG_REF_NAME==BASIC_util_vector_and_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_not_0_1/BASIC_util_vector_not_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_not_0_1 || ORIG_REF_NAME==BASIC_util_vector_not_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_not_0_2/BASIC_util_vector_not_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_not_0_2 || ORIG_REF_NAME==BASIC_util_vector_not_0_2} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_and_0_2/BASIC_util_vector_and_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_and_0_2 || ORIG_REF_NAME==BASIC_util_vector_and_0_2} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_and_0_3/BASIC_util_vector_and_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_and_0_3 || ORIG_REF_NAME==BASIC_util_vector_and_0_3} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_not_0_3/BASIC_util_vector_not_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_not_0_3 || ORIG_REF_NAME==BASIC_util_vector_not_0_3} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_sim_constant_0_3/BASIC_sim_constant_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_sim_constant_0_3 || ORIG_REF_NAME==BASIC_sim_constant_0_3} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_and_0_5/BASIC_util_vector_and_0_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_and_0_5 || ORIG_REF_NAME==BASIC_util_vector_and_0_5} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_util_vector_and_0_6/BASIC_util_vector_and_0_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_util_vector_and_0_6 || ORIG_REF_NAME==BASIC_util_vector_and_0_6} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_sim_constant_0_4/BASIC_sim_constant_0_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_sim_constant_0_4 || ORIG_REF_NAME==BASIC_sim_constant_0_4} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_xlslice_2bit_0_0/BASIC_xlslice_2bit_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_xlslice_2bit_0_0 || ORIG_REF_NAME==BASIC_xlslice_2bit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_xlconcat_8_0_0/BASIC_xlconcat_8_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_xlconcat_8_0_0 || ORIG_REF_NAME==BASIC_xlconcat_8_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_rom_memory_0_0/BASIC_rom_memory_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_rom_memory_0_0 || ORIG_REF_NAME==BASIC_rom_memory_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/ip/BASIC_sim_constant_0_5/BASIC_sim_constant_0_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BASIC_sim_constant_0_5 || ORIG_REF_NAME==BASIC_sim_constant_0_5} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/OLD/RISCV_FOR_COCOTB/RISCV.srcs/sources_1/bd/BASIC/BASIC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BASIC'. Do not add the DONT_TOUCH constraint.
