#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Jun 21 09:39:31 WEST 2026
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim RISCV_COCOTB_wrapper_behav -key {Behavioral:sim_1:Functional:RISCV_COCOTB_wrapper} -tclbatch RISCV_COCOTB_wrapper.tcl -protoinst "protoinst_files/RISCV_COCOTB.protoinst" -view /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/testes.wcfg -log simulate.log"
xsim RISCV_COCOTB_wrapper_behav -key {Behavioral:sim_1:Functional:RISCV_COCOTB_wrapper} -tclbatch RISCV_COCOTB_wrapper.tcl -protoinst "protoinst_files/RISCV_COCOTB.protoinst" -view /media/steckler/xilinx_linux/RISCV_ZYNQ/V2/RVI20U32/RV32I_COCOTB/RISCV_ZYNQ_ON_TEST/testes.wcfg -log simulate.log

